# Generated by Django 4.2.28 on 2026-05-20 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chipin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
