# Generated by Django 4.2.28 on 2026-05-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipin', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(choices=[(0.5, '★☆☆☆☆'), (1, '★☆☆☆☆'), (1.5, '★★☆☆☆'), (2, '★★☆☆☆'), (2.5, '★★★☆☆'), (3, '★★★☆☆'), (3.5, '★★★★☆'), (4, '★★★★☆'), (4.5, '★★★★★'), (5, '★★★★★')], decimal_places=1, max_digits=2),
        ),
    ]
