# Generated by Django 4.2.28 on 2026-05-13 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_game_profile_bio_profile_favourite_game_1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
