# Generated by Django 4.2.28 on 2026-05-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover',
            field=models.ImageField(default='game_covers/default.jpg', upload_to='game_covers/'),
        ),
    ]
