# Generated by Django 4.2.28 on 2026-05-20 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_game_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='max_spend',
        ),
    ]
